/* 
  Sketch generated by the Arduino IoT Cloud Thing "LEDControl" 
  Arduino IoT Cloud Variables description
  The following variables are automatically generated and updated when changes are made to the Thing
  
  bool led_state;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <Arduino_MKRIoTCarrier.h>
MKRIoTCarrier carrier;

uint32_t red = carrier.leds.Color(255, 0, 0);
uint32_t green = carrier.leds.Color(0, 255, 0);
uint32_t blue = carrier.leds.Color(0, 0, 255);
uint32_t yellow = carrier.leds.Color(255, 255, 0);
uint32_t cyan = carrier.leds.Color(0, 255, 255);
uint32_t off = carrier.leds.Color(0, 0, 0);

void setup() {
  carrier.begin();
  
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
}


/*
  Since LedState is READ_WRITE variable, onLedStateChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedStateChange()  {
  // Add your code here to act upon LedState change
  if (led_state == true)
  {
  carrier.leds.setPixelColor(0, red);     // Set LED 0 to red
  carrier.leds.setPixelColor(1, green);   // Set LED 1 to green
  carrier.leds.setPixelColor(2, blue);    // Set LED 2 to blue
  carrier.leds.setPixelColor(3, yellow);  // Set LED 3 to yellow
  carrier.leds.setPixelColor(4, cyan);    // Set LED 4 to cyan
  carrier.leds.show();
  }
  else
  {
  carrier.leds.setPixelColor(0, off);     // Set LED 0 to off
  carrier.leds.setPixelColor(1, off);   // Set LED 1 to off
  carrier.leds.setPixelColor(2, off);    // Set LED 2 to blue
  carrier.leds.setPixelColor(3, off);  // Set LED 3 to yellow
  carrier.leds.setPixelColor(4, off);    // Set LED 4 to cyan
  carrier.leds.show();
  }  
}
